### ISSUE TITLE
[BUG]: Error setting up entry Anna for plugwise - type conversion

### ISSUE THREAD

**Issue by bouwew** [plugwise/python-plugwise#158]
### Describe the bug.

When starting Home Assistant, I get a type error in the Anna plugin log. The integration is not set up. For exact error message, see the error log below.
I have been using the integration for a long time. In the 2022.3 release, it is not working anymore.

### Expected behavior

A working system.

### What version of Home Assistant Core has the issue?

2022.3

### What type of installation are you running?

Home Assistant Supervised

### How and which version of the integration do you have installed?

Home Assistant Core

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

4.2.1?

### Additional information

Logfile of Anna integration:

Logger: homeassistant.config_entries
Source: components/plugwise/gateway.py:53
First occurred: March 8, 2022, 10:35:28 PM (1 occurrences)
Last logged: March 8, 2022, 10:35:28 PM

Error setting up entry Anna for plugwise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/plugwise/__init__.py", line 13, in async_setup_entry
    return await async_setup_entry_gw(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/plugwise/gateway.py", line 53, in async_setup_entry_gw
    api.get_all_devices()
  File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 106, in get_all_devices
    self._all_device_data()
  File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 60, in _all_device_data
    data = self._get_device_data(device_id)
  File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 201, in _get_device_data
    device_data = self._get_appliance_data(dev_id)
  File "/usr/local/lib/python3.9/site-packages/plugwise/helper.py", line 897, in _get_appliance_data
    and self._outdoor_temp > data["cooling_activation_outdoor_temperature"]
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by bouwew** [comment]
@bart1970 let's continue the detailed discussion w.r.t. your problem here.

**Comment by bart1970** [comment]
Hi Bouwe,

Here are the files. The cooling is turned on (with dipswitch).

[modules.txt](https://github.com/plugwise/python-plugwise/files/8226053/modules.txt)
[appliances.txt](https://github.com/plugwise/python-plugwise/files/8226054/appliances.txt)
[direct_objects.txt](https://github.com/plugwise/python-plugwise/files/8226055/direct_objects.txt)
[domain_objects.txt](https://github.com/plugwise/python-plugwise/files/8226056/domain_objects.txt)
[locations.txt](https://github.com/plugwise/python-plugwise/files/8226057/locations.txt)

Small remark related to the instructions anonymisation. The appliances, domain_objects and direct_objects files also contained the IP address in one of the <measurement lines. Updated the IP address there also to 127.0.0.2.

**Comment by bouwew** [comment]
Thanks! I've downloaded them, you can remove them from the above message.

**Comment by bouwew** [comment]
Bart, a question, how did you end up with Elga as a device-name? Did you rename the OpenTherm device?

**Comment by bart1970** [comment]
You mean the device name in HA I assume. I'm not aware that I have changed this. I don't think I can find that back, can I?

**Comment by bouwew** [comment]
Yes, device name in HA. The thing is, we expect to see OpenTherm as device-name, not Elga.

A quick update, we have found why you see the error, now we need to think about how to solve it...

**Comment by bart1970** [comment]
Good you found it. Hope you can solve it. If I need to do any tests, please let me know.

Just checked some backups. 1.5 year ago, it was already called Elga. So if I changed it, it was already a long time ago.

**Comment by bouwew** [comment]
Yeah OK, makes sense. Due to the HA unique_id, then the name / sensorname stay the same. But I realize now that this does not cause the bug.

We have it working in our test-environment. And we will test in plugwise-beta.
You could help us testing by installing plugwise-beta as a custom_component. Would that be an option for you?

Plugwise-beta can replace Core plugwise 1-to-1, you would only need to install plugwise-beta and restart HA. Plugwise-beta should pick up the existing Plugwise integration so you would not need to do any additional configuration.

**Comment by CoMPaTech** [comment]
@bart1970 @bouwew pw-beta https://github.com/plugwise/plugwise-beta/releases/tag/v0.21.3a1 is available for testing from https://github.com/plugwise/plugwise-beta/pull/248

**Comment by bouwew** [comment]
@bart1970 are you able to test the updates for us?
There are 2 options:
  - Install plugwise-beta v0.21.3a2
  - Change the plugwise version in the HA Core files to 0.16.7

We're happy to provide help for both options, if needed.

**Comment by bart1970** [comment]
Was working until an hour ago. I will give it a try now and let you know if I managed.

**Comment by bouwew** [comment]
What will you try?

**Comment by bart1970** [comment]
I copied manually the files (using the file editor) in the custom folder and restarted HA.
Message I get now in the logs look like the old one, but just a little different:
022-03-11 20:41:45 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Anna for plugwise
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/plugwise/__init__.py", line 16, in async_setup_entry
return await async_setup_entry_gw(hass, entry)
File "/config/custom_components/plugwise/gateway.py", line 74, in async_setup_entry_gw
api.get_all_devices()
File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 92, in get_all_devices
self._all_device_data()
File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 54, in _all_device_data
data = self._get_device_data(device_id)
File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 226, in _get_device_data
device_data = self._device_data_climate(details, device_data)
File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 172, in _device_data_climate
if not self.cooling_active and self._outdoor_temp > device_data.get(
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by bouwew** [comment]
Which plugwise-version is shown in the `manifest.json` file?

**Comment by bart1970** [comment]
"version": "0.21.3a1",

**Comment by bouwew** [comment]
`plugwise==0.16.7` <-- that version I mean.

**Comment by bart1970** [comment]
Probably looking at the wrong file. I have in:
/config/custom_components/plugwise/manifest.json

{
  "domain": "plugwise",
  "name": "Plugwise Beta",
  "version": "0.21.3a1",
  "documentation": "https://github.com/plugwise/plugwise-beta",
  "after_dependencies": ["usb", "zeroconf"],
  "requirements": ["https://test-files.pythonhosted.org/packages/97/dd/c03345f77a98bdabd24ff1a8ac60eaf6be3c086126228074f7f66f0ed06e/plugwise-0.16.7a9.tar.gz#plugwise==0.16.7a9"],
  "codeowners": ["@CoMPaTech","@bouwew","@brefra"],
  "iot_class": "local_polling",
  "config_flow": true
}

**Comment by bouwew** [comment]
0.16.7a9, that should work. Why doesn't it work...
Well try some other things.

**Comment by bouwew** [comment]
@bart1970 I think we have solved your issue. Meaning, it works in our testing with the xml-data you provided.
Can you please test with https://github.com/plugwise/plugwise-beta/releases/tag/v0.21.4a1

**Comment by bart1970** [comment]
Today I am not at home. I hope I can test it tomorrow. After testing this, I updated my Ubuntu. That introduced very strange connectivity issues between te containers, but plugwise is in the standard HA container, so think I can test that.


Bouwe Westerdijk ***@***.***> schreef op 12 maart 2022 10:24:50 CET:
***@***.*** I think we have solved your issue. Meaning, it works in our testing with the xml-data you provided.

**Comment by bart1970** [comment]
Thanks! Initialisation works again. Looks fully working.

I do have a question, why are some entities in the configuration tab "sensors" (like elga outdoor temperature) and other entities "diagnostics" (like elga return temperature). Looks like a little artificial difference (maybe due to HA, not due to your integration). The diagnostic information page: [https://www.home-assistant.io/integrations/diagnostics/](url) doesn't help a lot.

**Comment by CoMPaTech** [comment]
Thanks for you feedback!

As for the entities, ran into that myself as well while writing another integration: It's a fairly recent functionality called entity category that does this (see https://developers.home-assistant.io/blog/2021/10/26/config-entity?_highlight=categ#entity-categories). The diagnostics integration 'just dumps' the JSON data, so they are related but not the same thing.

**Comment by bouwew** [comment]
Indeed, thanks, that's good news :)
Also great feedback, is appreciated. We'll consider changing this sensor to the diagnostics category.

We would like to ask you to test the cooling-related operation of the Plugwise-beta integration in detail, when the outdoor temperature is rising and the cooling mode becomes active, if this is possible for you.
We are wondering if our code is working correctly. It is mostly based on assumptions, we really need someone to test the correctness of these assumptions for us :)
If you can, please look at all the details: for instance, are all the `climate.anna` states shown correct in relation to what the Plugwise App shows? Please note, there is a time delay between what is show in the APP vs what is shown in HA.

**Comment by bouwew** [comment]
About your feedback, we have decided to not change.
Reason: the outdoor_temperature sensor can be available on both on the OpenTherm as the Smile (Adam/Anna) device.
On the OpenTherm device it should be a diagnostics sensor but on the Smile device it shouldn't be one.
Due our implementation it's not possible to separate between the sensors. The only way to fix this is by changing one of the sensor names but this will complicate the implementation in the python code.

**Comment by bart1970** [comment]
The cooling part is at this moment hard to test. For the heating part, some observations.
When the system is heating 
- The heating icon on the anna HA (Thermostat Card) is off.  The status line on the card is "Heating - Home" which is correct. (See picture below)
<img width="157" alt="image" src="https://user-images.githubusercontent.com/48695944/158060106-dfe84720-5022-4726-9916-e00a37920ecd.png">
The Elga values when ony heatpump:
<img width="170" alt="image" src="https://user-images.githubusercontent.com/48695944/158060178-8886910c-03ef-43e3-b792-1ea123c0de28.png">
With gas and heatpump:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/48695944/158060485-ee42628c-9b60-42d9-9fc9-aa4b240f1ecb.png">

If I have other observations, I'll let you know. What is the best way to contact you?

**Comment by bart1970** [comment]
The other observation was already in one of the other tickets. On HA, I can update the temperature (since this release) in steps of 0,1. On the Anna, only in steps of 0,5. Don't think is this is real problem.

**Comment by bouwew** [comment]
On the diagnostics sensor, when I take some time to look at it, it's not so hard :) More later.

On your observations:
The four icons on the climate card indicate the hvac_mode, from left to right:
- auto, means a schedule is active, heating or cooling happens based on a schedule
- heating, the heating is based on the manually set setpoint
- cooling, the heating is based on the manually set setpoint
- off, this is artificial mode, a mistake in my view, should not be there

Heating and Home, refer to hvac_action and selected preset.

**Comment by bart1970** [comment]
Why shoud the outdoor_temperature on the OpenTherm device a diagnostics sensor but on the Smile device not.
One is the real outdoor temperature (OpenTherm), the other I aassume based on some internet weather site?

**Comment by bouwew** [comment]
On the pictures, all looks as I would expect.

On the outdoor sensor, on the gateway there is one single sensor, it's common to show it as a plain sensor:
![image](https://user-images.githubusercontent.com/11290930/158061226-b6b349e0-727c-4b5a-8723-df1ba8617891.png)

**Comment by bouwew** [comment]
Best way to contact me: just keep posting in this topic. I receive a notice when somebody adds a new message to an existing topic, also when it's closed.

**Comment by bart1970** [comment]
Ah, I think I now understand the icons. Don't know if I find it logical however. If I read it correct, always only one icon is active.
I would expect: 
- One indication on how you configured your thermostat (for example auto, heating, off, cooling)
- In case of auto, the name of the program (for example: Home, Holiday, )
- One indication on what the system is really doing: Idle, cooling, heating.
Looks like they are now a little mixed up.

**Comment by bouwew** [comment]
Agree, I share your opinion. That's why I use the Simple Thermostat card instead: https://github.com/nervetattoo/simple-thermostat
![image](https://user-images.githubusercontent.com/11290930/158065101-c890fcca-4ac5-4f36-aae6-b52fa063aa17.png)

I can share my configuration for this card if it helps.

**Comment by bouwew** [comment]
On the control on the HA climate card or the Simple Thermostat card, the Plugwise integration can only turn the schedule off or on. So when you have a schedule active and the cooling mode is off, you could click on the cooling-icon/button and in the end the heating-icon will be shown as active :)

**Comment by bouwew** [comment]
This issue has been solved in v0.21.4 therefore closing this issue.

**Comment by bouwew** [comment]
@bart1970 Can you please test Plugwise v0.23.3a0?

I've made some changes that are specific with Anna connected to a device with cooling capability:
- `hvacmodes` are `heat_cool` and `auto'
- Attributes `temperature` replaced by `target_temp_high` and `target_temp_low`
- These two target_temps are displayed in the HA climate card.

Are these changes working in your system?

**Comment by bart1970** [comment]
Hi @bouwew 
Yes, but my NUC running Home assistant crashed two weeks ago. Needed to buy one and now make sure everything get working again first... Not much at home, so can take some time.

**Comment by bouwew** [comment]
@bart1970 Thanks for getting back to me, and sorry to hear about the server-problems.
Ok, please get back to me when you are for some testing :)

**Comment by bouwew** [comment]
@bart1970 Plugwise-beta v0.26.0 contains the latest Anna + Elga related updates. According to user huub66 all is working.
When you are up and running again, please let me know if you find anything out-of-order.
