### ISSUE TITLE
[TODO]: On the Adam the vacation-preset is no longer available

### ISSUE THREAD

**Issue by bouwew** [plugwise/python-plugwise#185]
### Todo

Both the Plugwise App and the local website don't show this preset anymore as a settable option.
Not as a preset:
![image](https://user-images.githubusercontent.com/11290930/167371683-33ad79b0-1bb9-4235-879d-f2a255409cd2.png)

Not as a schedule option:
![image](https://user-images.githubusercontent.com/11290930/167371936-ee017b87-ac5d-48d0-9f51-0520ff5bdbad.png)

@CoMPaTech Shall we remove it from the plugwise output for the Adam?

**Comment by wburgers** [comment]
Hey guys, sorry to comment on this older topic, but I can still use the vacation preset on my Adam.

![image](https://user-images.githubusercontent.com/2129305/192378338-75657604-9c72-4860-961f-e7efed951414.png)

Plugwise changed it to an action that requires extra input.
When I click the button to set a preset for all rooms on the main page, I get the following:
![image](https://user-images.githubusercontent.com/2129305/192378454-d1732646-3926-46e4-9b3f-9833ba3e454e.png)
![image](https://user-images.githubusercontent.com/2129305/192378492-58e500ed-2e00-4ee7-9764-9500eef2d66c.png)

I previously misused the vacation preset as a 'relaxing at home' preset.
My home preset was used as 'working at home'.
I find setting several temperatures in sequence from HA is a little unreliable and sometimes Adam keeps the previously set setpoint, which is pretty annoying.
I don't know if the API can still set the vacation preset mode.
Hopefully Plugwise will soon implement custom presets, as that would be awesome 🤞.
I don't like scheduling my Adam, so I don't use that at all.

Anyway, if you need any info on my system, let me know.

Cheers!

**Comment by bouwew** [comment]
Thanks for reporting! Reopening this issue.

**Comment by bouwew** [comment]
I've tried the Vakantie and Pauze option, it looks like they are quite similar to HA Automations.

I think the best action is to re-add the removed vacation-preset for the Adam.

**Comment by frenck** [comment]
It's on my system available as well.

**Comment by bouwew** [comment]
Solved ( = add back vacation preset for Adam) in v0.23.0
