### ISSUE TITLE
[TODO]: Expose type hints

### ISSUE THREAD

**Issue by epenet** [plugwise/python-plugwise#231]
### Todo

Type hints are in the code, but they are not seen by `mypy` in Home Assistant

I think `mypy` is not getting the type hints through because the library is missing a `py.typed` file

See https://github.com/home-assistant/core/pull/80722#discussion_r1001739234

**Comment by bouwew** [comment]
Thanks for the feedback @epenet! We'll implement the suggestions shortly.

**Comment by bouwew** [comment]
Implemented in https://github.com/plugwise/python-plugwise/releases/tag/v0.31.2 and https://github.com/home-assistant/core/pull/92253
