### ISSUE TITLE
[IMPROVE] Print statements

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise#25]
**Describe the improvement**
Rewrite print-statements to _LOGGER statements

From findings during #24

**Comment by CoMPaTech** [comment]
@brefra can you have a look at the `if self.print_progress:` then `print` statements in `stick.py`? First glance as @bouwew mentioned they might just become _LOGGER.debug statements, having said that - probably just using _LOGGER.debug might also skip all the if-statement.

**Comment by brefra** [comment]
All print statements are leftovers from the early days for use the lib standalone directly from cli. Not really an usecase anymore.
I'll prepare a PR to get them removed.
