### ISSUE TITLE
[IMPROVE] If statements for booleans/trilean state

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise#27]
**Describe the improvement**

Evaluate rewriting `if something_somewhere is True:` to `if something`. This goes for `None`, `False` and `True` (hence trilean). It won't be possible everywhere (we have a specific case in `plugwise-beta` where we needed it like that, but most of them should be rewritable in `python-plugwise`.

From findings during #24

**Comment by bouwew** [comment]
Let's be careful with shortening `if something is None:` and `if something is not None:`.
I remember from the early days that in many cases we have to use/leave it at `if something is not None:`

**Comment by CoMPaTech** [comment]
Yup, hence the reference to our earlier experience :)

**Comment by bouwew** [comment]
Fixed in #30
