### ISSUE TITLE
[IMPROVE] Solve complexity

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise#28]
Describe the improvement

Linter checks bring to light more complexity that we should solve. They are marked as `TODO` in #24 and onwards and disabled for linting using `# noqa: 901`! Some have a complexity of over 40.

While it's not a necessity it would be best to at least have a look at why their complexity is marked high. For reference see https://www.flake8rules.com/rules/C901.html

From findings during #24

**Comment by brefra** [comment]
@CoMPaTech, are we ready to close this issue?
While quickly scanning the current TODO's there are no flake8 related ones left

**Comment by CoMPaTech** [comment]
Not really, we changed coveragerc to cover only smile :(

**Comment by CoMPaTech** [comment]
So when time is availble we should clean out .coveragerc and start improving

**Comment by CoMPaTech** [comment]
Added #131
