### ISSUE TITLE
[FEATURE]: Rewrite to match/case

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise#567]
### Describe the solution you are looking for

Also see #565 comment on rewriting the if statements to match/cases

### Is your feature request related to a problem? (optional)

Just an idea that came up

### Describe alternatives you've considered

Leaving as be - there is no harm in the current set up

### What type of installation are you running?

Home Assistant OS

### How did you install python-plugwise (or `plugwise`) for short

HA using HACS

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

n/a

### Your setup

n/a

### Additional context

n/a

**Comment by bouwew** [comment]
Implemented via #572
