### ISSUE TITLE
[FEATURE] Switch for DHW 

### ISSUE THREAD

**Issue by tansuka** [plugwise/python-plugwise#63]
First of all, thank you very much for the great integration, all your hard work and time. Really appreciated 👏 

**Is your feature request related to a problem? Please describe.**
I have a stupid opentherm boiler (Remeha Calenta) that doesn't heat the domestic hot water on demand. Only option to have the hot water is to turn on DHW Comfort mode on the boiler (via an opentherm thermostat). If I keep DHW Comfort on, it uses a lot of gas and keeps the water warm all the time, even though I don't need it which costs money and not good for the environment. 

**Describe the solution you'd like**
On the Plugwise Adam interface, there is a toggle under Settings -> Heating System -> Heating -> Advanced Settings to turn on DHW Comfort mode on or off. A good way is to have a switch on HA to turn this on and off instead of going to Plugwise interface every time. This will also allow me to set up reminders if I leave hot water on for a long time and use smart assistants with voice to turn on/off. After we have the switch in HA, the possibilities are endless. 

**Home Assistant (please complete the following information):**
- Version | core-2021.2.2
- Installation Type | Home Assistant OS
 - Installed plugwise version: HA-core
 - Installed through: 'Core

**Plugwise product and setup (please complete the following information):**
 - Type: Adam
 - Firmware: [check through the app or the integrations page in Home Assistant]
 - Setup: Plugwise Lisa, Toon

**Additional context**
I did a bit research, the status of the switch can be get from 
GET: {APPLIANCES}/core/appliances;id={appl_id}
endpoint from the following element
```
<domestic_hot_water_toggle id="XXXXX"/>
<updated_date>2021-02-11T02:46:42.165+01:00</updated_date>
<type>domestic_hot_water_comfort_mode</type>
<state>off</state>
</toggle_functionality>
```

and the status get be set with 
PUT: {APPLIANCES};id= {appl_id}/toggle;type=domestic_hot_water_comfort_mode
with the following XML as data 
```
<toggle><state>{state}</state></toggle>
```
possible states are off and on

Thank you very much again and have a great day!

**Comment by bouwew** [comment]
I'll have a look, will report back.

**Comment by tansuka** [comment]
> Update: the set-function is working already :)
> 
> I'll have a look, will report back.

That’s damn fast! 😂

**Comment by bouwew** [comment]
The set-function was easy, with good input :+1: 

Adding the switch in HA Core is much harder...

**Comment by bouwew** [comment]
![image](https://user-images.githubusercontent.com/11290930/107687660-0e49fc00-6ca7-11eb-8761-296eb448f54c.png)

Looks like it's working.

Are you using Plugwise-beta? If not, please install. I'll create a Plugwise-beta test-version.

**Comment by bouwew** [comment]
Please install and test https://github.com/plugwise/plugwise-beta/releases/tag/0.14.1a3

**Comment by tansuka** [comment]
Coincidentally, just _before_ I install the test, my home assistant crashed. as soon as it's up and running again, I'll install & test

Thank you very much

**Comment by tansuka** [comment]
Sorry, took a bit longer to make HA work again, somehow couldn't install 1a3 via HACS, had to copy under custom_components manually. 

However, after all the these hassle, it works like a charm!! 

Thank you very much for the super fast response and implementation.  I owe you a beer :)

**Comment by bouwew** [comment]
Great, thanks for testing!

I will integrate this feature in a better way, test it some more, and then release the feature as part of the v0.14.1 release.

**Comment by bouwew** [comment]
@tansuka I've created a new release: v0.14.1a4. Please install and quickly test this version.
Please note: I had to make some changes & improvement "under the hood" which causes a new sensor to appear with the name ending at "_2". You can delete the old switch and then rename the new switch by removing the "_2" part.

**Comment by tansuka** [comment]
Hello @bouwew, 

Sorry for the late reply, it was busy at home.

I have just installed and tested the new version. It works without any problem. on the upcoming days I can tested more but, it works as intended so far. 

Thank you very much.

**Comment by bouwew** [comment]
@tansuka Plugwise-beta v0.14.1 has been released, adding the DHW Comfort Mode switch

**Comment by bouwew** [comment]
@tansuka Please try v0.14.3, in that version the switch is called `switch.auxiliary_dhw_comfort_mode`.
And it can be found under the Plugwise Auxiliary device.
