### ISSUE TITLE
Anna/Smile with hybrid setup Elga+gas boiler - only detect boiler burning

### ISSUE THREAD

**Issue by jessesteinen** [plugwise/python-plugwise#80]
I have a hybrid setup with an Elga heatpump connected to a Remeha Quinta boiler for central heating, and a Plugwise Anna.
Now the integration in HA only shows when the boiler is heating. When the Elga is working (I’m monitoring its power draw separately) but the boiler isn’t, then the card shows that it’s idle.

Is this a matter of configuration or maybe a limitation of the integration? Anna is connected (using OpenTherm) to the Elga, which is connected to the gas boiler, so I would expect Anna to understand that Elga is ‘burning’ as well? Is this setup, without Adam, supported? I'd rather not shell out again for an Adam, whose further functionality I have no need of, just to get the monitoring right in HA :)

XMLs attached, many thanks for any assistance!

**Comment by jessesteinen** [comment]
[Archive.zip](https://github.com/plugwise/python-plugwise/files/6313631/Archive.zip)

**Comment by bouwew** [comment]
Ok, thanks for providing the files.

I've had a quick look and I don't see any indication in the data that points to two heating-devices. So I'm thinking there is, at the moment, no support enabled for your configuration.
My advise would be to contact Plugwise and ask them if you Anna can be made to support your configuration.
I know from Plugwise that for the Adam you need to pay a little extra to enable the support for your configuration. So it could be that this is needed for your Anna too. Or, they will suggest you to add an Adam.

I've deleted your file as it contained sensitive private information.

**Comment by jessesteinen** [comment]
Thank you, bouwew! I thought I had stripped the files of any sensitive data as per the directions, what did I miss?

The [Plugwise website](https://www.plugwise.com/product/anna-2/?lang=en) states that Anna supports a hybrid setup with e.g. an Elga, but also that they charge 50 euros for enabling 'advanced support'. Just not sure what that entails exactly. I will contact them and report back here.

Something else that may or may not be relevant: I never get to see the heatpump icon (not in the PW app either), just the flame symbol for the gas boiler. And when I let the app figure out what heater I have, it results in OT for the protocol but everything else is 'unknown'.

**Comment by bouwew** [comment]
Ok, I did not know that the Anna did support such a config too, but, it makes sense.

I suspect you will need to pay the 50 euro, after that they will upgrade your Anna and then it should work.
Question is, will then the Plugwise integration work. If not, send the files again and we should be able to make it work.

You're right, I see that you've removed the sensitive data from the provided files.

**Comment by bouwew** [comment]
Closed, the Anna needs a software update.

**Comment by jessesteinen** [comment]
Hi @bouwew, do you mean the paid update from PW? I sent a mail to them last week but still awaiting their reply. If you can confirm you mean that paid update, then I'm fine with closing the issue. Thanks for your time (and I will report back if it does indeed resolve my issue).

**Comment by bouwew** [comment]
Yes, that's what I mean.

If you end up getting the update, and it doesn't work, please reopen this issue and we'll take it from there.

**Comment by jessesteinen** [comment]
I've got the paid Anna upgrade, and after some fiddling the Smile-T correctly recognises the Elga now. For the moment I have disabled the PW integration in HA, so tomorrow during the day I will check with just the Smile/Anna connected. If that works, I'll switch to HA again and report back my findings.

**Comment by jessesteinen** [comment]
I think it's working correctly now, but I find that HA updates very slowly compared to the app. Is there a reason _not_ to reduce the update interval from 60s to e.g. 10s in the integration options?

**Comment by bouwew** [comment]
Great! Would you mind posting a picture showing the entities that are under the Auxiliary Device?

That's why we added the OPTION to set the interval to you own liking :)

**Comment by jessesteinen** [comment]
> That's why we added the OPTION to set the interval to you own liking :)
Yeah, I figured as much, but other than cutting down on the chat on the local network and some increase in local CPU usage, I guess there are no adverse affects?

The entities under aux device look like this for me:
<img width="1060" alt="Screenshot 2021-04-21 at 19 59 44" src="https://user-images.githubusercontent.com/5107889/115599877-5bb49c00-a2dc-11eb-947c-3b06a2204df3.png">

**Comment by bouwew** [comment]
Reopening the issue.

@jessesteinen I'm missing at least one sensor: Auxiliary Device State, and possibly more.
Which Plugwise integration are you using? HA Core Plugwise? 
If yes, would you mind "upgrading" to the plugwise-beta custom_component: https://github.com/plugwise/plugwise-beta
Plugwise-beta is much further ahead in development, more features/sensors, and it's quite stable.

You only need to install the custom_component and then restart HA Core, it is fully compatible with the HA Plugwise component.

**Comment by jessesteinen** [comment]
I'm using the PW integration that comes with HA by default (I assume that's the HA Core Plugwise integration, yes). I'll give the beta a spin and post back another screenshot of the entities under the aux device.

**Comment by jessesteinen** [comment]
Here you go:
<img width="332" alt="Screenshot 2021-04-22 at 09 30 14" src="https://user-images.githubusercontent.com/5107889/115673894-69563a00-a34d-11eb-88bd-5db6f022a704.png">

**Comment by bouwew** [comment]
It's still missing, the aux device state sensor.
Is there any information in HA Logs? I'm kind of expecting that there is an error there because of the missing sensor.

**Comment by jessesteinen** [comment]
`HACS is ratelimited, HACS will resume setup when the limit is cleared (10:14:52)`

I need to wait this out :)

**Comment by jessesteinen** [comment]
I cannot find anything in the logs relevant to this, no relevant errors at all.

**Comment by bouwew** [comment]
Ok, then please capture and send fresh xml-data as you did before. 
It would be good to have the system in the heating state when you capture the xml-data.

**Comment by jessesteinen** [comment]
Here you go (taken while heating)!
[Archive.zip](https://github.com/plugwise/python-plugwise/files/6359988/Archive.zip)

small correction: In the xml cleaning instructions a field <mac-address> is mentioned but it's actually <mac_address> (with an underscore). Also the modules file, at least in my case, contains no mac addresses.

**Comment by bouwew** [comment]
Thanks! I'll have a look.

**Comment by bouwew** [comment]
I already know what the problem is, the problem is me :)
I was thinking too much of the Adam while you have an Anna.
For your system the Auxiliary Device State sensor is not there. Because you only have one thermostat, the heating/cooling/idle state is shown as part of the climate-entity. 

So, in your system all is as it should be :)

**Comment by jessesteinen** [comment]
Good to hear our non-issue is resolved now :) Thanks your efforts and time looking into my situation!

**Comment by jessesteinen** [comment]
I think it's still not working properly (or at least, as I expected): at this moment in time the heatpump is active (see Elga power consumption) but the Anna shows in HA that it is idle. The PW app on my phone shows that the heatpump is active.

<img width="385" alt="Screenshot 2021-04-30 at 10 06 45" src="https://user-images.githubusercontent.com/5107889/116667075-0c393480-a99c-11eb-9218-0355216ffe08.png">
<img width="393" alt="Screenshot 2021-04-30 at 10 06 49" src="https://user-images.githubusercontent.com/5107889/116667084-0f342500-a99c-11eb-804e-f554854a1fdb.png">
![IMG_0461](https://user-images.githubusercontent.com/5107889/116667139-1fe49b00-a99c-11eb-93ec-b3c137c63e09.jpeg)

**Comment by bouwew** [comment]
Ok noted. I will have a detail look at the data you sent before, which was captured under the same circumstances: the system was heating? I'll do this later today/tomorrow.

**Comment by jessesteinen** [comment]
Yes it was heating when I previously captured the xmls. Thanks!

**Comment by bouwew** [comment]
I looked at the files you sent before, in there I can see that the parameter that the heating-state in plugwise-beta is based in, is on. So that should result in the "Heating - Home".

I would need to look at xml-data that is captured when your system is exactly at the same state as you reported above here.

It could be that your system was running the compressor to collect heat or heat up before the actual heating-process would start.
I have an airco at work that works in the same during winter-time: I can hear the system (compressor) running while no hot air comes out, that starts to happen a little later.

**Comment by bouwew** [comment]
@jessesteinen I just realized we don't have a complete implementation covering the cooling function of the Elga, see https://github.com/plugwise/plugwise-beta/issues/171
I was wondering, would you be willing in helping me in fixing this issue?

**Comment by jessesteinen** [comment]
I’d be happy to! But please note that I don’t use cooling, only heating, so not sure if I can still help then?

**Comment by bouwew** [comment]
Ok, yes, then I assumed wrong, sorry.

**Comment by bouwew** [comment]
@jessesteinen can this issue be closed?

**Comment by jessesteinen** [comment]
absolutely, thanks for your help.
