### ISSUE TITLE
lots of Elga errors in notifications

### ISSUE THREAD

**Issue by jessesteinen** [plugwise/python-plugwise#81]
Hi,

Not sure if this is even a plugwise related issue, or something with my Elga heatpump/boiler combination, but only since I have integrated it in HA I'm seeing these errors. Of course, before I didn't have anywhere to see it, yet maybe someone could shed some light on what is happening.

I am getting a lot of notifications about issues between the Elga and my (Remeha Quinta 35c) boiler. This is over a period of 5 days, the errors seem to pop up randomly:
`Error: The Techneco Elga cannot read its NTC2 supply temperature sensor.`
`Error: The Techneco Elga cannot communicate with its slave OpenTherm boiler.`
`Error: The OpenTherm boiler slaved to the Techneco Elga has a fault.`
`Error: The Techneco Elga cannot read its NTC1 return temperature sensor.`
`Error: There is no OpenTherm communication with the boiler.`
`Error: The Techneco Elga cannot communicate with its slave OpenTherm boiler.`
`Error: The OpenTherm boiler slaved to the Techneco Elga has a fault.`
`Error: The OpenTherm boiler slaved to the Techneco Elga has a fault.`
`Error: The Techneco Elga's pump cannot generate sufficient water flow.`
`Error: The Techneco Elga cannot read its additional external temperature sensor.`
`Error: The Techneco Elga cannot read its NTC2 supply temperature sensor.`
`Error: The Techneco Elga cannot read its NTC1 return temperature sensor.`
`Error: The boiler indicates something is wrong.`
`Error: The Toshiba board used by the Techneco Elga has a fault.`

Occasionally I see in the log entries like below, but these do not map to the times when the notifications are sent:
`2021-04-26 14:58:09 ERROR (MainThread) [custom_components.plugwise.gateway] Timeout fetching Smile Anna data`
`2021-04-22 18:10:04 ERROR (MainThread) [plugwise.helper] Smile response empty or error in <?xml version="1.0" encoding="UTF-8"?>
<error>
<code>400 Bad Request</code>
<message>XML validation failed: Extra element setpoint in interleave
(document):1: Element thermostat_functionality failed to validate content
</message>
</error>`
`2021-04-22 18:10:04 ERROR (MainThread) [custom_components.plugwise.climate] Error while communicating to device`

Interestingly, the Elga hasn't been heating all that time as the indoor temperature was > setpoint all the time.

I'm on Home Assistant OS, core-2021.4.6, using plugwise-beta 1.11.3 (I'm now updating to 1.12.3 to see if it makes any difference).

Maybe @bouwew you recognise any of this?

Many thanks!

**Comment by bouwew** [comment]
Plugwise-beta v1.11.3, 1.12.3? I don't recognize the numbers? The latest version of plugwise beta is v0.14.6.

On the Elga errors, in my system (Intergas CV ketel) I sometimes see similar error messages but the frequency is much lower.
These errors should show in the Plugwise App as well but likely they are only temporary so they disappear again. And then you don't noticed them unless you look at the App when such a message has just appeared.

In plugwise-beta we have chosen to make these messages persistent, we were curious to see what is going on under the hood.
You can disable the notification sensor, then these messages should no longer appear.

The other log entries are all about a (temporary?) bad connection between the Smile and your network.

**Comment by bouwew** [comment]
@jessesteinen can this issue be closed?

**Comment by jessesteinen** [comment]
absolutely, thanks for your help.
