### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [plugwise/python-plugwise#97]
**Describe the bug**
It would be very helpful if you could tag releases as well. This would enable distributions to use the source tarball from GitHub instead of PyPI.

Was done in the past could be a glitch in the workflow.

Thanks

**Comment by bouwew** [comment]
Hi @fabaff,
What are you looking for exactly? Is tagging like e.g. `v0.12.0 ` what you asking for?

**Comment by fabaff** [comment]
> What are you looking for exactly? Is tagging like e.g. v0.12.0 what you asking for?

The latest release on PyPI is [0.13.0](https://pypi.org/project/plugwise/0.13.0/). The latest GitHub release is [0.12.0](https://github.com/plugwise/python-plugwise/releases/tag/v0.12.0).

**Comment by bouwew** [comment]
Ok, is that the reason why you are asking.

Well, v0.13.0 contains a bug, that's why we haven't made a formal release. v0.13.1 will be the next formal release.

Your reason for this issue makes me curious, why are you asking us to create a release? What is you interest in this software?

**Comment by fabaff** [comment]
The package for Nix/NixOS is using GitHub as the origin for the source. Personally I prefer to use the upstream source rather than PyPI. Often there is not much difference between those tarballs but sometimes only the upstream tarball contains the test suite or the license file.

`plugwise` is a Home Assistant dependency.

**Comment by CoMPaTech** [comment]
Same here (in terms of personal preference), but I always thought the preferred way was PyPi nowadays :) Having tests and licenses as a difference is a good call though! But as Bouwe indicates, the .13 was 'almost ready' but not released.

**Comment by bouwew** [comment]
Ok, thanks for explaining.

As I don't know NixOS, a warning: plugwise is at first and foremost the backend library for the custom_component plugwise-beta. Only the designated version as in the homeassistant requirements-all.txt file is compatible with the Home Assistant plugwise component. Make sure not to mix versions!

**Comment by bouwew** [comment]
v0.13.1 has been released and tagged.

**Comment by fabaff** [comment]
Thank you
